### ISSUE TITLE
Unable to find package for @io_bazel_rules_rust//rust:rust.bzl

### ISSUE THREAD

**Issue by nickdecooman** [wildarch/blackjack#15]
Hello,

When running `//:blackjack`, Bazel returns the following error:

> ERROR: error loading package '': at /private/var/tmp/_bazel_nickdecooman/79cdfbeb69263a0131a37a2814065174/external/blackjack/blackjack.bzl:1:6: Unable to find package for @io_bazel_rules_rust//rust:rust.bzl: The repository '@io_bazel_rules_rust' could not be resolved: Repository '@io_bazel_rules_rust' is not defined.

WORKSPACE.bazel:
```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "rules_rust",
    sha256 = "cf2e82c56c73c3213bc2d94303aee88d7e44634ad1e1fe183befa85b17b5021d",
    strip_prefix = "rules_rust-0e3593fc5d839e4a74523f07e885b761ee19e662",
    urls = [
        # Master branch as of 2021-12-19
        "https://github.com/bazelbuild/rules_rust/archive/0e3593fc5d839e4a74523f07e885b761ee19e662.tar.gz",
    ],
)

load("@rules_rust//rust:repositories.bzl", "rust_repositories")

rust_repositories()

http_archive(
    name = "blackjack",
    url = "https://github.com/wildarch/blackjack/archive/f9d49ea9f93aabcea0fa9d8e90cb854c7a1de9ce.zip",
    sha256 = "496410e369ee6a986f223071d47c5f69302abaf41840a5f3451000ee5f4739bd",
    strip_prefix = "blackjack-f9d49ea9f93aabcea0fa9d8e90cb854c7a1de9ce",
)

load("@blackjack//:workspace.bzl", "blackjack_cargo")

blackjack_cargo()
```

BUILD.bazel:
```
load("@blackjack//:blackjack.bzl", "blackjack")

blackjack(name = "blackjack")
```

I was also able to reproduce this error by running the [no_dependencies](https://github.com/wildarch/blackjack/tree/master/tests/no_dependencies) example (did replace the local blackjack import in the WORKSPACE file by loading it via http_archive)

**Comment by wildarch** [comment]
Hi Nick,

Looking at the url for the blackjack http_archive, it seems you are pulling in an old version (my bad, I forgot to update the README.md with the new url).

Can you try with the new url instead:

```
http_archive(
    name = "blackjack",
    url = "https://github.com/wildarch/blackjack/archive/909b66db4782cf963791aa4a24793244dffdba17.zip",
    strip_prefix = "blackjack-909b66db4782cf963791aa4a24793244dffdba17",
)
```

I have also updated this on the README.

**Comment by nickdecooman** [comment]
Yes, this is working now! Thanks so much 🙌
